# Generated by Django 3.1.7 on 2021-02-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(db_index=True, max_length=140, verbose_name='Body')),
                ('image_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Image Name')),
                ('line_count', models.PositiveIntegerField(default=0, verbose_name='Like Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
            ],
        ),
    ]
