# Generated by Django 3.1.7 on 2021-02-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tweet',
            table='tweet',
        ),
    ]
