# Generated by Django 3.1.7 on 2021-02-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210220_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='line_count',
            new_name='like_count',
        ),
    ]
