# Generated by Django 3.1.7 on 2021-02-25 04:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_tweet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image_name',
        ),
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
