# Generated by Django 3.1.7 on 2021-02-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20210225_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Like Count'),
        ),
    ]
